/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrackRouteImport } from './routes/track'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OrderCodeRouteImport } from './routes/order.$code'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated/courses.$id'
import { Route as ApiPublicAgentDownloadRouteImport } from './routes/api/public/agent-download'
import { Route as ApiPublicAgentDownloadDotexeRouteImport } from './routes/api/public/agent-download[.]exe'
import { Route as ApiPublicAgentVersionRouteImport } from './routes/api/public/agent-version'
import { Route as ApiPublicBuildVersionRouteImport } from './routes/api/public/build-version'
import { Route as ApiPublicCardTransactionsRouteImport } from './routes/api/public/card-transactions'
import { Route as ApiPublicIceServersRouteImport } from './routes/api/public/ice-servers'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1.products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAgentDownloadRoute = ApiPublicAgentDownloadRouteImport.update({
  id: '/api/public/agent-download',
  path: '/api/public/agent-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentDownloadDotexeRoute =
  ApiPublicAgentDownloadDotexeRouteImport.update({
    id: '/api/public/agent-download.exe',
    path: '/api/public/agent-download.exe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentVersionRoute = ApiPublicAgentVersionRouteImport.update({
  id: '/api/public/agent-version',
  path: '/api/public/agent-version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildVersionRoute = ApiPublicBuildVersionRouteImport.update({
  id: '/api/public/build-version',
  path: '/api/public/build-version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardTransactionsRoute =
  ApiPublicCardTransactionsRouteImport.update({
    id: '/api/public/card-transactions',
    path: '/api/public/card-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIceServersRoute = ApiPublicIceServersRouteImport.update({
  id: '/api/public/ice-servers',
  path: '/api/public/ice-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-download.exe': typeof ApiPublicAgentDownloadDotexeRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/build-version': typeof ApiPublicBuildVersionRoute
  '/api/public/card-transactions': typeof ApiPublicCardTransactionsRoute
  '/api/public/ice-servers': typeof ApiPublicIceServersRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-download.exe': typeof ApiPublicAgentDownloadDotexeRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/build-version': typeof ApiPublicBuildVersionRoute
  '/api/public/card-transactions': typeof ApiPublicCardTransactionsRoute
  '/api/public/ice-servers': typeof ApiPublicIceServersRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/order/$code': typeof OrderCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-download.exe': typeof ApiPublicAgentDownloadDotexeRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/build-version': typeof ApiPublicBuildVersionRoute
  '/api/public/card-transactions': typeof ApiPublicCardTransactionsRoute
  '/api/public/ice-servers': typeof ApiPublicIceServersRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/order/$code'
    | '/product/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/courses/$id'
    | '/api/public/agent-download'
    | '/api/public/agent-download.exe'
    | '/api/public/agent-version'
    | '/api/public/build-version'
    | '/api/public/card-transactions'
    | '/api/public/ice-servers'
    | '/api/public/v1/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/order/$code'
    | '/product/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/courses/$id'
    | '/api/public/agent-download'
    | '/api/public/agent-download.exe'
    | '/api/public/agent-version'
    | '/api/public/build-version'
    | '/api/public/card-transactions'
    | '/api/public/ice-servers'
    | '/api/public/v1/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/order/$code'
    | '/product/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/courses/$id'
    | '/api/public/agent-download'
    | '/api/public/agent-download.exe'
    | '/api/public/agent-version'
    | '/api/public/build-version'
    | '/api/public/card-transactions'
    | '/api/public/ice-servers'
    | '/api/public/v1/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  McpRoute: typeof McpRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OrderCodeRoute: typeof OrderCodeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAgentDownloadRoute: typeof ApiPublicAgentDownloadRoute
  ApiPublicAgentDownloadDotexeRoute: typeof ApiPublicAgentDownloadDotexeRoute
  ApiPublicAgentVersionRoute: typeof ApiPublicAgentVersionRoute
  ApiPublicBuildVersionRoute: typeof ApiPublicBuildVersionRoute
  ApiPublicCardTransactionsRoute: typeof ApiPublicCardTransactionsRoute
  ApiPublicIceServersRoute: typeof ApiPublicIceServersRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent-download': {
      id: '/api/public/agent-download'
      path: '/api/public/agent-download'
      fullPath: '/api/public/agent-download'
      preLoaderRoute: typeof ApiPublicAgentDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-download.exe': {
      id: '/api/public/agent-download.exe'
      path: '/api/public/agent-download.exe'
      fullPath: '/api/public/agent-download.exe'
      preLoaderRoute: typeof ApiPublicAgentDownloadDotexeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-version': {
      id: '/api/public/agent-version'
      path: '/api/public/agent-version'
      fullPath: '/api/public/agent-version'
      preLoaderRoute: typeof ApiPublicAgentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-version': {
      id: '/api/public/build-version'
      path: '/api/public/build-version'
      fullPath: '/api/public/build-version'
      preLoaderRoute: typeof ApiPublicBuildVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card-transactions': {
      id: '/api/public/card-transactions'
      path: '/api/public/card-transactions'
      fullPath: '/api/public/card-transactions'
      preLoaderRoute: typeof ApiPublicCardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ice-servers': {
      id: '/api/public/ice-servers'
      path: '/api/public/ice-servers'
      fullPath: '/api/public/ice-servers'
      preLoaderRoute: typeof ApiPublicIceServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  McpRoute: McpRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OrderCodeRoute: OrderCodeRoute,
  ProductSlugRoute: ProductSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAgentDownloadRoute: ApiPublicAgentDownloadRoute,
  ApiPublicAgentDownloadDotexeRoute: ApiPublicAgentDownloadDotexeRoute,
  ApiPublicAgentVersionRoute: ApiPublicAgentVersionRoute,
  ApiPublicBuildVersionRoute: ApiPublicBuildVersionRoute,
  ApiPublicCardTransactionsRoute: ApiPublicCardTransactionsRoute,
  ApiPublicIceServersRoute: ApiPublicIceServersRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
